name: e2e-mobile-tests

on: workflow_dispatch

jobs:
  build:
    name: 'Run tests - browserstack'
    runs-on: ubuntu-latest

    steps:
    - name: 'Browserstack env setup'
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_KEY }}
        
    - name: 'Nightwatch tests'
      uses: actions/checkout@v2
      with:
          node-version: 18
          cache: 'npm'
    - run: npm install
    - name: Run tests
      run: npm run runAndroidTestsBrowserstack
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

    - name: Archive reports
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: /home/runner/work/nightwatchjsMobileAutomationStudy/nightwatchjsMobileAutomationStudy/tests_output/*

    - name: "Publish test results"
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with: 
        github_token: ${{ secrets.PAGE_TOKEN }}
        publish_dir: './tests_output/nightwatch-html-report'
        force_orphan: true
        keep_files: true


